version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: finance-tracker-db
    environment:
      POSTGRES_DB: finance_tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - finance-tracker-network

  app:
    build: .
    container_name: finance-tracker-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/finance_tracker?schema=public
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - finance-tracker-network
    command: npm run dev

volumes:
  postgres_data:

networks:
  finance-tracker-network:
    driver: bridge
